-- FILE: createSalesTable.sql
-- Date: Nov. 19, 23
-- PURPOSE: CREATE SALES TABLE
---------------------------------------------------------------

-- Create SALES table
CREATE TABLE SALES (
    SALES_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    CUSTOMER_ID INT,
    EMPLOYEE_ID INT,
    DATE_PURCHASE DATE,
    QUANTITY INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
