-- FILE: createTables.sql
-- Date: Nov. 19, 23
-- PURPOSE: CREATE TABLES
---------------------------------------------------------------

-- Create CUSTOMER table
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255)
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    HIRE_DATE DATE,
    SALARY DECIMAL(10, 2),
    JOB_TITLE VARCHAR(255)
);

-- Create PRODUCT table
CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PNAME VARCHAR(255),
    AVAILABILITY INT,
    PRICE DECIMAL(10, 2),
    DESCRIPTION VARCHAR(255)
);

-- Create SALES table
CREATE TABLE SALES (
    SALES_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    CUSTOMER_ID INT,
    EMPLOYEE_ID INT,
    DATE_PURCHASE DATE,
    QUANTITY INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- Create PAYMENT table
CREATE TABLE PAYMENT (
    PAYMENT_ID INT PRIMARY KEY,
    SALES_ID INT,
    CUSTOMER_ID INT,
    COST DECIMAL(10, 2),
    PAYMENT_TYPE VARCHAR(255),
    FOREIGN KEY (SALES_ID) REFERENCES SALES(SALES_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
